blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/SatoNozomi44/MyTask-List/issues/new?template=custom.md&projects=SatoNozomi44%2FMyTask-List%2F1&labels=MyTask-List
